server:
  port: 8082

spring:
  application:
    name: main-service

  datasource:
    url: jdbc:mysql://localhost:3306/main_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
